//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BaiHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiHoc()
        {
            this.BinhLuan = new HashSet<BinhLuan>();
            this.Images = new HashSet<Images>();
        }
    
        public int IdBaiHoc { get; set; }
        public int IdUser { get; set; }
        public int IdLBH { get; set; }
        [Required]
        [Display(Name = "Tiêu Đề")]
        public string TieuDe { get; set; }
        [Display(Name = "Tóm Tắt")]
        public string TomTat { get; set; }
        public string UrlHinh { get; set; }
        [Display(Name = "Ngày Đăng")]
        public System.DateTime Ngay { get; set; }
        [Display(Name = "Nội Dung")]
        public string Content { get; set; }
        [Display(Name = "Số Lần Xem")]
        public Nullable<int> SoLanXem { get; set; }
        public string KeyWords { get; set; }
        [Display(Name = "Ẩn Hiện")]
        public bool AnHien { get; set; }
    
        public virtual LoaiBaiHoc LoaiBaiHoc { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
    }
}
