//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EF : DbContext
    {
        public EF()
            : base("name=EF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaiHoc> BaiHoc { get; set; }
        public virtual DbSet<BinhLuan> BinhLuan { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<Like> Like { get; set; }
        public virtual DbSet<LoaiBaiHoc> LoaiBaiHoc { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
