//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LoaiBaiHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiBaiHoc()
        {
            this.BaiHoc = new HashSet<BaiHoc>();
        }
        public int IdLBH { get; set; }
        [Display(Name = "Tên Loại Bài")]
        public string Ten { get; set; }
        [Display(Name = "Thứ Tự")]
        public int ThuTu { get; set; }
        [Display(Name = "ID Cha")]
        public Nullable<int> Id_LBH { get; set; }
        public string KeyWords { get; set; }
        [Display(Name = "Mô tả")]
        public string MoTa { get; set; }
        [Display(Name = "Ẩn Hiện")]
        public bool AnHien { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiHoc> BaiHoc { get; set; }
    }
}
